### ISSUE TITLE
django templates support

### ISSUE THREAD

**Issue by dev72** [CRBroughton/htmx-attributes#4]
Hello,
please add support for django templates also.

Thank you.

**Comment by CRBroughton** [comment]
Hi there, and thanks for opening an issue! 

I can't make any guarantees I'd ever look into additional language support (really is dependant on what I'm working on) however this would be a fantastic first issue for the project if you'd like to add in support yourself, and adding in additional language support should be relatively trivial if you already have Python setup on your machine. 

There are some basic guidelines for contributing, with you can find at the bottom of the README.md file. As I don't use Python, it might be a good idea for whoever picks this up, to include a small proof that their implementation is working correctly (perhaps a gif/video?).
