### ISSUE TITLE
Autocomplete .astro vs .html

### ISSUE THREAD

**Issue by malofu** [CRBroughton/htmx-attributes#7]
I'm having an issue using the extension with .astro files. When I start writing "hx" and then click the dash key the extension closes the help window. This is not happening on .html files. i.e:

xxxx.html
<div hx[full list] ...
...
<div hx-sw [hx-swap, hx-swap-oob]

xxxx.astro
<div hx[full list] ...
...
<div hx- (Bye list)

I'm the only one with this issue? Thanks

![image](https://github.com/user-attachments/assets/a10c8474-dc34-446c-8876-7880d0f040e5)

**Comment by CRBroughton** [comment]
Hi there! This seems to be more of an issue with the Astro file type or language server itself as I can easily replicate this problem with any attribute that has a dash in, examples would be any `aria-` attributes.
