### ISSUE TITLE
Astro file: unexpected token issue 

### ISSUE THREAD

**Issue by Rob-Dinsdale** [CRBroughton/htmx-attributes#8]
Hi,

When using either the following syntax in Astro files the use of the two colons is causing an unexpected token issue error.

 hx-on::after-request 

or 

hx-on:htmx:after-request 

Thanks for the extention.

**Comment by CRBroughton** [comment]
Hi there! This issue appears to be more related to Astro than to the extension itself - https://github.com/CRBroughton/htmx-attributes/issues/7 I'll close this issue AFAIK this issue is upstream
